apiVersion: apps/v1
kind: Deployment

metadata:
  name: managelab
  namespace: managelab

spec:
  replicas: 3

  selector:
    matchLabels:
      app: managelab

  template:
    metadata:
      labels:
        app: managelab

    spec:
      containers:
      - name: managelab
        image: priscilaz/managelab:v1

        imagePullPolicy: Always

        ports:
        - containerPort: 8080